angular2:
  restart: always
  build: ./angular2/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
web:
  restart: always
  build: .
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app
    - /usr/src/app/static
  env_file: sleepdiary_backend/.prod.env
  environment:
    DEBUG: 'true'
  command: /usr/local/bin/gunicorn sleepdiary_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3

postgres:
  restart: 'true'
  build: ./postgres
  env_file:
    - sleepdiary_backend/.prod.env
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

